# Generated by Django 4.2.1 on 2023-09-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('hora', models.DateField(max_length=50)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=250)),
                ('local', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
