# Generated by Django 4.2.1 on 2023-09-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_fecha_alter_evento_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
