# Generated by Django 4.2.1 on 2023-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
