# Generated by Django 4.2.1 on 2023-09-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_remove_local_id_alter_local_nombre_and_more'),
        ('eventos', '0005_alter_evento_fecha_alter_evento_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.local'),
        ),
    ]
