# Generated by Django 4.2.1 on 2023-09-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ubicacion',
        ),
    ]
