# Generated by Django 6.0.4 on 2026-05-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
