# Generated by Django 4.2.1 on 2023-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_remove_local_id_alter_local_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='estado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='local',
            name='imagen',
            field=models.ImageField(default='ruta/a/imagen_por_defecto.jpg', upload_to=''),
        ),
    ]
