# Generated by Django 4.2.1 on 2023-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_local_estado_local_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
