# Generated by Django 4.2.1 on 2023-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0004_alter_local_estado_alter_local_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.ImageField(upload_to='images/locals/%d'),
        ),
    ]
