# Generated by Django 6.0.4 on 2026-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0006_alter_local_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='imagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
