# Generated by Django 4.2.1 on 2023-11-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nommbre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=50)),
            ],
        ),
    ]
